require: rubocop-rails

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Style/NegatedIfElseCondition:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - Gemfile
    - config/**/*
    - db/**/*
    - bin/**/*
    - node_modules/**/*
