Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

AllCops:
  Exclude:
    - Gemfile
    - config/routes.rb
    - db/**/*
    - bin/**/*
    - node_modules/**/*
