ruby "2.2.2"
source "https://rubygems.org"

gem "rails", "4.2.11.1"
gem "mysql2"
gem "devise", "~> 3.5"
gem "bcrypt", "~> 3.1.7"
gem "haml"
gem "bootstrap-sass", "~> 3.3.4"
gem "sass-rails", ">= 3.2"
gem "font-awesome-sass"
gem "simple_form"
gem "momentjs-rails", "~> 2.9"
gem "uglifier", ">= 1.3.0"
gem "jquery-rails"
gem "turbolinks"
gem "axlsx_rails"
gem "delayed_job_active_record"
gem "whenever", require: false

group :development, :test do
  gem "byebug"
  gem "spring", ">= 1.3.6"
  gem "dotenv-rails"
  gem "awesome_print"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "shoulda-matchers"
  gem "database_cleaner"
  gem "faker"
end
