default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOSTNAME"] %>
  port: <%= ENV["DB_PORT"] %>
  socket: <%= ENV["SOCKET"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>_production
  sslkey: /etc/mysql/client-key.pem
  sslcert: /etc/mysql/client-cert.pem
  sslca: /etc/mysql/ca.pem
  sslcapath: /etc/mysql
